version: '3'

services:
  backend:
    container_name: 'fastapi-users-management'
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/logs